default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: demo_user
  password: 12345678
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: demo_db

test:
  <<: *default
  database: demo_db

production:
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: sample_app_production
  username: sample_app
  password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>
