maximum_length_name: 50
maximum_length_email: 255
minimum_length_pass: 6
page_number: 5
paginate_user: 25
paginate_post: 30
option: 80
post_size: 50
content_value: 1140
maximum_length_pass: 128
reset_password_within: 6
RAILS_ADMIN_PAGINATION: 5
user:
  gravatar_size: 80
  gravatar_big_size: 200
  gravatar_size_small: 50
  gravatar_post_size: 42
  gravatar_size_mini: 25
